#!/usr/bin/env python3
"""Regenerate the README's "On the Air" section: symbol diagrams of our
packets and of one repeater slot.

Every air-time number comes from the firmware's constants (lora_air.py reads
them from the source), so change a constant, run this, and the diagrams
follow. The turnaround numbers (how fast a repeater relays) are measured:
medians from a relay-test.py capture, the newest one unless given.

The section sits between two marker comments in README.md; everything
between them is replaced. Edit this script, not the README section.

Usage:
    python3 scripts/air-diagram.py                       # newest out/relay-test/ capture
    python3 scripts/air-diagram.py out/relay-test/20261004-093952
    python3 scripts/air-diagram.py --print               # show it, don't touch README.md
"""

import os
import re
import statistics
import sys
import textwrap

import lora_air as air

README = os.path.join(air.ROOT, "README.md")
CAPTURES = os.path.join(air.ROOT, "out", "relay-test")
BEGIN = "<!-- air-diagram: generated by scripts/air-diagram.py; edit the script, not this section -->"
END = "<!-- /air-diagram -->"

INDENT = 7  # diagram rows start after a ruler label ("symbol ", "ms     ")
WRAP = 128  # the README's prose width


def para(text):
    """A paragraph or bullet, wrapped like the rest of the README"""
    indent = "  " if text.startswith("- ") else ""
    return textwrap.fill(text, WRAP, subsequent_indent=indent, break_on_hyphens=False)


def main():
    args = [a for a in sys.argv[1:] if a != "--print"]
    capture = args[0] if args else newest_capture()
    measured = measure(capture) if capture else None
    section = render(measured, capture)
    if "--print" in sys.argv:
        print(section)
        return
    with open(README) as f:
        text = f.read()
    if BEGIN not in text or END not in text:
        sys.exit(f"README.md has no {BEGIN!r} ... {END!r} markers")
    start = text.index(BEGIN)
    end = text.index(END) + len(END)
    with open(README, "w") as f:
        f.write(text[:start] + section + text[end:])
    print(f"README.md: On the Air regenerated ({os.path.relpath(capture, air.ROOT) if capture else 'no capture'})")


# --- measured: medians from a relay-test capture ---------------------------

LINE = re.compile(r"^[IWE] \((\d+)\) [^ ]+: (.*)$")
AT_US = re.compile(r" at=(\d+)us")
TX_END = re.compile(r"TX end \[26B\] \d+ms: standby=(\d+)us prep=(\d+)us tx=(\d+)us back_to_rx=(\d+)us at=(\d+)us")


def newest_capture():
    """The newest capture with a repeater that relayed something"""
    if not os.path.isdir(CAPTURES):
        return None
    for name in sorted(os.listdir(CAPTURES), reverse=True):
        path = os.path.join(CAPTURES, name)
        boards = load(path)
        if "repeater" in boards and any(m.startswith("RELAY ") for _, m in boards["repeater"]):
            return path
    return None


def load(path):
    """{role: [(log ms, message)]}, each board's role from its boot line"""
    boards = {}
    for name in os.listdir(path):
        if not name.endswith(".log"):
            continue
        lines = []
        with open(os.path.join(path, name), errors="replace") as f:
            for raw in f:
                m = LINE.match(raw.strip())
                if m:
                    lines.append((int(m.group(1)), m.group(2)))
        mode = next((re.search(r"mode=(\w+)", m).group(1) for _, m in lines if "Config: mode=" in m), None)
        role = {"normal": "handheld"}.get(mode, mode)
        if role:
            boards[role] = lines
    return boards


def measure(path):
    """Medians, in ms: each repeater step, and the talker's PTT timings"""
    boards = load(path)
    steps = {"rx_to_relay": [], "standby": [], "prep": [], "tx": [], "back_to_rx": [], "slack": []}
    lines = boards.get("repeater", [])
    for i, (_, msg) in enumerate(lines):
        if not msg.startswith("RELAY [26B]"):
            continue
        rx_end = next((lines[j][1] for j in range(i - 1, max(i - 6, -1), -1) if lines[j][1].startswith("RX end [26B]")), None)
        tx_end = next((lines[j][1] for j in range(i, min(i + 8, len(lines))) if lines[j][1].startswith("TX end [26B]")), None)
        if not rx_end or not tx_end:
            continue
        rx_done = int(AT_US.search(rx_end).group(1)) / 1000
        standby, prep, tx, back, at = (int(v) / 1000 for v in TX_END.search(tx_end).groups())
        in_rx = at  # the TX end line is logged as the radio is back in RX
        steps["rx_to_relay"].append(in_rx - (standby + prep + tx + back) - rx_done)
        steps["standby"].append(standby)
        steps["prep"].append(prep)
        steps["tx"].append(tx)
        steps["back_to_rx"].append(back)
        # The talker's next packet starts PERIOD after this one started
        steps["slack"].append(rx_done - air.AIR_MS + air.PERIOD_MS - in_rx)
    ptt = {"wake": [], "voice": []}
    hand = boards.get("handheld", [])
    for i, (ms, msg) in enumerate(hand):
        if not msg.startswith("PTT pressed"):
            continue
        after = hand[i + 1 : i + 40]
        wake = next((tx_started(t, m) for t, m in after if re.match(r"TX end \[\d+B\].* preamble=", m)), None)
        voice = next((tx_started(t, m) for t, m in after if m.startswith("TX end [26B]")), None)
        if wake is not None:
            ptt["wake"].append(wake - ms)
        if voice is not None:
            ptt["voice"].append(voice - ms)
    medians = {k: statistics.median(v) for k, v in {**steps, **ptt}.items() if v}
    medians["relays"] = len(steps["slack"])
    return medians


def tx_started(ms, msg):
    """When a send went on the air, from its TX end line (logged at ms):
    before the end by its air (tx=) and the way back to listening"""
    m = re.search(r"tx=(\d+)us back_to_rx=(\d+)us", msg)
    return ms - (int(m.group(1)) + int(m.group(2))) / 1000


# --- drawing ---------------------------------------------------------------


def fmt(x):
    """1.0 -> '1', 4.25 -> '4.25', 12.288 -> '12.3'"""
    if abs(x - round(x)) < 1e-9:
        return str(round(x))
    if abs(x * 4 - round(x * 4)) < 1e-9:
        return f"{x:g}"
    return f"{x:.1f}"


def box(fields, rows, symbols):
    """A field diagram, roughly one character per symbol. fields: (width in
    symbols, label); rows: lines of cell text below the labels, None
    merging a cell into the one before. Rulers mark every edge, in symbols
    and ms."""
    widths = [max(round(sym) - 1, len(label) + 2, 3) for sym, label in fields]
    border = " " * INDENT + "+" + "+".join("-" * w for w in widths) + "+"
    edges = [INDENT]
    for w in widths:
        edges.append(edges[-1] + w + 1)

    def ruler(name, values):
        out = list(name.ljust(edges[-1] + 10))
        last = -1
        for col, v in zip(edges, values):
            if v is None or col <= last:
                continue
            for k, ch in enumerate(v):
                out[col + k] = ch
            last = col + len(v)
        return "".join(out).rstrip()

    def row(cells):
        line, k = " " * INDENT + "|", 0
        while k < len(cells):
            span = 1
            while k + span < len(cells) and cells[k + span] is None:
                span += 1
            width = sum(widths[k : k + span]) + span - 1
            line += cells[k][:width].center(width) + "|"
            k += span
        return line

    at, sym_ruler, ms_ruler = 0.0, [], []
    for sym in [0] + [s for s, _ in fields]:
        at += sym
        sym_ruler.append(fmt(at))
        ms_ruler.append(fmt(at * air.symbol_ms()))
    # Label every edge only where there's room: blocks get their ends only
    keep = symbols
    sym_ruler = [v if k in keep else None for k, v in enumerate(sym_ruler)]
    ms_ruler = [v if k in keep else None for k, v in enumerate(ms_ruler)]
    return "\n".join(
        [ruler("symbol", sym_ruler), border, row([label for _, label in fields])]
        + [row(r) for r in rows]
        + [border, ruler("ms", ms_ruler)]
    )


def packet_box(n_bytes, preamble, notes):
    blocks = air.payload_blocks(n_bytes)
    per = air.symbols_per_block()
    fields = [(preamble, "preamble"), (air.SYNC_SYMBOLS, "sync"), (air.HEADER_BLOCK_SYMBOLS, "PHY")]
    fields += [(per, f"B{k}") for k in range(1, blocks + 1)]
    rows = [[notes[0], fmt(air.SYNC_SYMBOLS), "header"] + [notes[2]] + [None] * (blocks - 1),
            [notes[1], "sym", f"{air.HEADER_BLOCK_SYMBOLS} sym"] + [notes[3]] + [None] * (blocks - 1)]
    if len(notes) > 4:
        rows.append(["", "", ""] + [notes[4]] + [None] * (blocks - 1))
    edges = [0, 1, 2, 3, len(fields)]
    return box(fields, rows, edges)


def bytes_box():
    frames = air.FRAMES_PER_PACKET
    hdr = air.HEADER_BYTES
    fb = air.CODEC2_FRAME_BYTES
    w = 11
    cells = [("our header", f"({hdr} bytes)", "", "")] + [
        ("Codec2", f"frame {k}", f"{fb} bytes", f"= {fmt(air.frame_ms())} ms") for k in range(1, frames + 1)
    ]
    widths = [15] + [w] * frames
    border = " " * INDENT + "+" + "+".join("-" * x for x in widths) + "+"
    ruler = list("byte".ljust(INDENT + sum(widths) + len(widths) + 6))
    col, offset = INDENT, 0
    for k, x in enumerate([hdr] + [fb] * frames):
        for i, ch in enumerate(str(offset)):
            ruler[col + i] = ch
        col += widths[k] + 1
        offset += x
    for i, ch in enumerate(str(offset)):
        ruler[col + i] = ch
    lines = ["".join(ruler).rstrip(), border]
    for r in range(4):
        lines.append(" " * INDENT + "|" + "|".join(c[r].center(x) for c, x in zip(cells, widths)) + "|")
    lines.append(border)
    return "\n".join(lines)


def header_box():
    widths = [max(len(f"{name} {bits}b") + 2, bits * 2 - 1) for bits, name in air.HEADER_FIELDS]
    border = " " * INDENT + "+" + "+".join("-" * w for w in widths) + "+"
    ruler = list("bit".ljust(INDENT + sum(widths) + len(widths) + 4))
    col, top = INDENT + 1, sum(b for b, _ in air.HEADER_FIELDS) - 1
    for (bits, _), w in zip(air.HEADER_FIELDS, widths):
        hi, lo = str(top), str(top - bits + 1)
        for i, ch in enumerate(hi):
            ruler[col + i] = ch
        for i, ch in enumerate(lo):
            ruler[col + w - len(lo) + i] = ch
        col += w + 1
        top -= bits
    cells = "|".join(f"{name} {bits}b".center(w) for (bits, name), w in zip(air.HEADER_FIELDS, widths))
    return "\n".join(["".join(ruler).rstrip(), border, " " * INDENT + "|" + cells + "|", border])


def slot_diagram(m):
    """One slot to scale, two symbols per character, with the measured
    repeater steps placed from the talker's packet start"""
    sym = air.symbol_ms()
    base, per_char = 10, 2

    def col(ms):
        return base + round(ms / sym / per_char)

    air_end = air.AIR_MS
    relay_start = air_end + m["rx_to_relay"]
    on_air = relay_start + m["standby"] + m["prep"]
    tx_done = on_air + m["tx"]
    in_rx = tx_done + m["back_to_rx"]
    period = air.PERIOD_MS
    width = col(period) + 24

    def blank():
        return [" "] * width

    def put(r, c, text):
        for k, ch in enumerate(text):
            if 0 <= c + k < width:
                r[c + k] = ch

    rows = []
    r = blank()
    put(r, 0, "symbol")
    for ms in (0, air_end, tx_done, period):
        put(r, col(ms), fmt(round(ms / sym, 2)) if ms in (0, air_end, period) else str(round(ms / sym)))
    rows.append(r)
    r = blank()
    for ms in (0, air_end, tx_done, period):
        r[col(ms)] = "|"
    rows.append(r)
    r = blank()
    put(r, 0, "talker")
    for k in range(col(0), col(air_end)):
        r[k] = "="
    r[col(0)], r[col(air_end)] = "[", "]"
    put(r, col(0) + 4, " voice packet n ")
    put(r, col(period), "[== packet n+1")
    rows.append(r)
    r = blank()
    put(r, 0, "repeater")
    for k in range(col(0) + 1, col(air_end)):
        r[k] = "."
    put(r, col(0) + 2, " RX (locked) ")
    r[col(air_end)] = "]"
    for k in range(col(air_end) + 1, col(on_air)):
        r[k] = "t"
    r[col(on_air)] = "["
    for k in range(col(on_air) + 1, col(tx_done)):
        r[k] = "="
    r[col(tx_done)] = "]"
    put(r, col(on_air) + 6, " relay of packet n ")
    for k in range(col(tx_done) + 2, col(period)):
        r[k] = "."
    r[col(tx_done) + 1] = "b"
    put(r, col(tx_done) + 3, " RX ")
    r[col(period)] = "["
    rows.append(r)
    r = blank()
    put(r, col(air_end) + 1, f"^ t: RX done -> relay on air {on_air - air_end:.1f} ms")
    rows.append(r)
    r = blank()
    put(r, col(tx_done) + 1, f"^ b: back to RX {m['back_to_rx']:.1f} ms")
    rows.append(r)
    r = blank()
    put(r, col(in_rx) + 1, f"<-- slack {m['slack']:.1f} ms -->")
    rows.append(r)
    r = blank()
    put(r, 0, "ms")
    for ms in (0, air_end, tx_done, period):
        put(r, col(ms), f"{ms:.1f}" if ms not in (0, period) else fmt(ms))
    rows.append(r)
    return "\n".join("".join(x).rstrip() for x in rows)


# --- the section -----------------------------------------------------------


def render(m, capture):
    sf, bw, cr = air.SPREADING_FACTOR, air.BANDWIDTH_KHZ, air.CODING_RATE
    sym = air.symbol_ms()
    pb, hb = air.PACKET_BYTES, air.HEADER_BYTES
    voice_sym, voice_ms = air.packet_symbols(pb), air.AIR_MS
    blocks = air.payload_blocks(pb)
    bpb = air.bits_per_block()
    capacity = blocks * bpb
    used = 8 * pb + 16
    wake = air.wake_preamble_symbols()
    eot_sym, eot_ms = air.packet_symbols(hb), air.packet_ms(hb)
    slot_sym = air.PERIOD_MS / sym
    spare = capacity - used
    header_extra = 4 * (sf - 7) if sf > 7 else 0
    cad_window = (wake - air.CAD_SYMBOLS) * sym

    out = [BEGIN, f"## On the Air (SF{sf} / {bw} kHz)", ""]
    out.append(
        f"LoRa SF{sf}, {bw} kHz, coding rate 4/{4 + cr}, explicit header, {air.PREAMBLE_SYMBOLS}-symbol preamble "
        f"(`core/src/air.rs`). One symbol is 2^{sf} / {bw} kHz = **{sym:.3f} ms**. Air times are Semtech's formula on our "
        f"constants; regenerate this section with `python3 scripts/air-diagram.py` after changing one."
    )
    out += ["", f"### Voice packet: {pb} bytes, {fmt(voice_sym)} symbols, {voice_ms:.1f} ms", "", "```"]
    out.append(packet_box(pb, air.PREAMBLE_SYMBOLS, [f"{air.PREAMBLE_SYMBOLS} sym", "", f"{blocks} blocks x {air.symbols_per_block()} sym",
                                                      f"{bpb} bits each = {capacity} bits", f"= {pb} B payload + 2 B CRC"]))
    out += ["```", ""]
    out.append(f"- **sync**: 2 sync-word symbols + 2.25 start-of-frame symbols")
    out.append(
        "- **CRC**: ours (`core/src/crc.rs`, CRC-16/CCITT-FALSE), appended and checked by the radio driver, with LoRa's own "
        "CRC off: the same 16 bits on the air. LoRa only checks its CRC if the received header says there is one, and noise "
        "can corrupt a header into \"no CRC\" and still pass its checksum; ours is checked on every packet, so garbage never "
        "reaches the app"
    )
    out.append(
        f"- **PHY header**: 20 bits (payload length, coding rate, CRC flag (off), header checksum), always sent at CR 4/8: "
        f"{air.HEADER_BLOCK_SYMBOLS} symbols" + (f", which also carry the first {header_extra} payload bits" if header_extra else f" (at SF{sf}, nothing else fits)")
    )
    fit = "exactly" if spare < 8 else f"with {spare} bits to spare"
    out.append(
        f"- **blocks**: each {air.symbols_per_block()}-symbol block carries {bpb} data bits. {pb} bytes + CRC fill {blocks} blocks "
        f"{fit}; one more byte {'costs' if spare < 8 else 'is free; the next block costs'} another block "
        f"(+{air.symbols_per_block()} symbols, +{air.symbols_per_block() * sym:.1f} ms)"
    )
    out += ["", f"The {pb} bytes:", "", "```", bytes_box(), "", "our header, 16 bits, big-endian (core/src/packet.rs):", header_box(),
            "       type: 0 voice, 1 echo replay, 2 wake, 3 voice end, 4 echo end (core/src/packet.rs PacketType)",
            "       txid: random per transmission; hops: repeaters this copy came through, 0 from the talker; spare: 0", "```", ""]
    out += [f"### Wake packet: {hb} bytes, {fmt(air.packet_symbols(hb, wake))} symbols, {air.packet_ms(hb, wake):.1f} ms", ""]
    out.append(
        f"Sent once, first, so radios sweeping the hop channels can find the transmission. The preamble takes up the air the "
        f"audio would have used, so it fits a slot like any packet: {air.PREAMBLE_SYMBOLS} + ({air.payload_symbols(pb)} − "
        f"{air.payload_symbols(hb)}) = {wake} symbols."
    )
    out += ["", "```"]
    wb = air.payload_blocks(hb)
    out.append(box([(wake, "preamble"), (air.SYNC_SYMBOLS, "sync"), (air.HEADER_BLOCK_SYMBOLS, "PHY")]
                   + [(air.symbols_per_block(), f"B{k}") for k in range(1, wb + 1)],
                   [[f"{wake} sym: a sweeping radio's CAD", fmt(air.SYNC_SYMBOLS), "header", f"{hb} B hdr"] + [None] * (wb - 1),
                    [f"({air.CAD_SYMBOLS} sym) can land in the first", "sym", f"{air.HEADER_BLOCK_SYMBOLS} sym", "+ CRC"] + [None] * (wb - 1),
                    [f"{wake - air.CAD_SYMBOLS} symbols ({cad_window:.0f} ms)", "", "", ""] + [None] * (wb - 1)],
                   [0, 1, 2, 3, 3 + wb]))
    out += ["```", ""]
    name_bytes = pb - hb - 6
    out += [f"### End packet (EOT): {pb} bytes, {fmt(voice_sym)} symbols, {voice_ms:.1f} ms", ""]
    out.append(
        f"The last packet of every transmission says who sent it and where they were: a voice packet's size and air, so it "
        f"fits a repeater's slot like one. The talker sends its own; a repeater relays it unchanged; an echo station ends "
        f"its replay with its own. The screen shows who was last heard, how far away, and through a repeater or not."
    )
    out += ["", "```"]
    out.append(f"byte   {0:<16}{hb:<12}{hb + 3:<12}{hb + 6:<33}{pb}")
    out.append("       +---------------+-----------+-----------+" + "-" * 32 + "+")
    out.append("       |  our header   | latitude  | longitude |" + f"name, UTF-8, up to {name_bytes} bytes".center(32) + "|")
    out.append("       | type 3 or 4   | 24 bits   | 24 bits   |" + "zero-padded".center(32) + "|")
    out.append("       +---------------+-----------+-----------+" + "-" * 32 + "+")
    out.append("       latitude: ±90° in ±2^23 steps (~1.2 m); longitude: ±180° (~2.4 m); -2^23 latitude = no fix")
    out += ["```"]
    out += ["", "### A transmission", "", "```", "PTT pressed"]
    wake_at = f"+{m['wake']:.0f} ms" if m and "wake" in m else "first"
    voice_at = f"~{m['voice']:.0f} ms" if m and "voice" in m else "then"
    out.append(f"{wake_at:>8}   wake packet         {fmt(air.packet_symbols(hb, wake))} sym   (sent while the first {air.PERIOD_MS:.0f} ms of audio is captured)")
    out.append(f"{voice_at:>8}   voice packet 0      {fmt(voice_sym)} sym   then one voice packet every {air.PERIOD_MS:.0f} ms ({fmt(slot_sym)} sym)")
    out.append("     ...")
    out.append(f" release   last voice packet, then EOT    {fmt(voice_sym)} sym  (who and where)")
    out += ["```", "", "An echo station sends its wake packet one slot before its replay. A repeater relays a wake packet like any other "
            "(once per transmission), so radios that only hear the repeater can find it.", ""]
    out.append(f"### One slot with a repeater: {air.PERIOD_MS:.0f} ms = {fmt(slot_sym)} symbols")
    out.append("")
    if not m or "slack" not in m:
        out = [para(line) if not line.startswith(("#", "<!--", "```", "|", " ")) and "\n" not in line else line for line in out]
        out += ["(No relay-test capture with a repeater: run `scripts/relay-test.py`, then this script.)", END]
        return "\n".join(out)
    rel = os.path.relpath(capture, air.ROOT)
    out.append(
        f"Talkers don't hop yet (`tx_hops = 0`): every transmission stays on the start slot, channel 0. Receivers sweep "
        f"`rx_hops` channels, and with the sweep flag a repeater relays each packet on the next of those after the one it "
        f"heard it on (channel 1 here), then goes back to listening on channel 0. It relays as soon as it has the packet, "
        f"inside the gap before the talker's next one. Repeater steps are medians of {m['relays']} relays (the "
        f"talker's packets and the echo station's replays) measured on the desk (`{rel}`)."
    )
    out += ["", "```", slot_diagram(m), "```", ""]
    rows = [
        ("RX done → relay starts", m["rx_to_relay"], "`t`: read the packet out, the app hands it back to the radio"),
        ("standby", m["standby"], "`t`"),
        ("prep (packet, modulation, buffer)", m["prep"], "`t`"),
        ("tx: TX command → TxDone", m["tx"], f"{voice_ms:.1f} ms on the air + PA ramp and IRQ"),
        ("back to RX", m["back_to_rx"], "`b`"),
    ]
    out += ["| Step (repeater) | Median | Symbols | |", "|---|---|---|---|"]
    for name, ms, note in rows:
        out.append(f"| {name} | {ms:.1f} ms | {ms / sym:.1f} | {note} |")
    out.append(f"| **slack before packet n+1** | **{m['slack']:.1f} ms** | **{m['slack'] / sym:.1f}** | "
               f"a relay ending later than this deafens the repeater to the next packet |")
    used_ms = air.PERIOD_MS - m["slack"]
    out += ["", f"Each repeater uses ~{used_ms:.0f} of the {air.PERIOD_MS:.0f} ms. A second repeater in the chain can't fit the "
            f"same slot on the same channel; that's what hopping (each repeater relays on the next channel) is for.", END]
    out = [para(line) if not line.startswith(("#", "<!--", "```", "|", " ")) and "\n" not in line else line for line in out]
    return "\n".join(out)


if __name__ == "__main__":
    main()
